### ISSUE TITLE
Unable to test with cookie

### ISSUE THREAD

**Issue by anonhunter** [hihackthis/burstPopUp#3]
I Choose option B, but it returns error, please check
B) To test with one custom cookie 
Then I enter cookie name and then its value as asked  but it always ask to check it.

**Comment by hihackthis** [comment]
Hi,

Here is normal:

![caseCook1](https://github.com/hihackthis/autoKNOXSS/assets/19677459/31ba34a3-3257-4c38-bbaa-b05caf02a753)

What custom cookie did you enter?

**Comment by anonhunter** [comment]
here it is
target.Web.SessionId
and its value a asked

**Comment by hihackthis** [comment]
Please detail your cookie here, in this format:

`name:value`

**Comment by hihackthis** [comment]
Remembering, burstPopUp follows the RFCs to the cookies and headers:

[Cookies and headers names and values](https://github.com/hihackthis/burstPopUp#cookies-and-headers-names-and-values)

:sunglasses:
